### PR TITLE
Fix bug: Update reMarkable API url

### PR DESCRIPTION
**Pull request by lapwat**
Update auth url according to last remapy commit: https://github.com/peerdavid/remapy/commit/abfc632eb5cb89521d929e41e68e5b8e5877bf81

### CODE REVIEW

**Comment by pouwerkerk** [comment]
Thanks @lapwat for making this change! I've tested it against registering and refreshing the device token.

Does the `deviceDesc` need to be 'mobile-android' now? Or can this change be omitted?

**Comment by lapwat** [comment]
I did not test desktop-windows neither. Feel free to chose whichever you want.

**Comment by lapwat** [comment]
Hello, can you merge please ? I have tested and it successfully worked.

**Comment by greynguyen** [comment]
@pouwerkerk can we merge this please? The library is currently unusable without this change

cc @Ogdentrod

**Comment by pouwerkerk** [comment]
I don't think you're waiting on my approval, since I don't have merge rights. But, yes I would also like to see this change accepted and I continue to use this branch in my projects as I wait for them to be merged in.

**Comment by lapwat** [comment]
@duongdangng @pouwerkerk You can use my fork in the meantime: https://github.com/lapwat/reMarkable-typescript

```json
{
  "dependencies": {
    "remarkable-typescript": "lapwat/reMarkable-typescript",
  }
}
```

For typescript users, you may have to do this after `npm install / yarn`:

```sh
cd node_modules/remarkable-typescript
npm install # or yarn
```

**Comment by matsgm** [comment]
> Thanks @lapwat for making this change! I've tested it against registering and refreshing the device token.
> 
> Does the `deviceDesc` need to be 'mobile-android' now? Or can this change be omitted?

Only the URLs needs to be updated.

**Comment by lapwat** [comment]
I have added those changes to my PR.

https://github.com/Ogdentrod/reMarkable-typescript/pull/21

**Comment by cvburgess** [comment]
When using this fork I get `HTTPError: Response code 400 (Bad Request)` on register().

Is there an easy way to get better logs from the `got` client? It seems the way some calls are made their errors get swallowed and its hard to debug.

**Comment by cvburgess** [comment]
The issue ended up being that you cannot set `deviceDesc` to an arbitrary value without getting a 400

**Comment by benoitsepe** [comment]
LGTM, thanks!

**Comment by benoitsepe** [comment]
and published in `remarkable-typescript@1.1.3`

**Pull request merged**
